name: ASCII artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        -   name: Checkout Repo
            uses: actions/checkout@v4

        -   name: checkput repo files
            run: ls -ltra

        -   name: Execute shell script
            run: |
                chmod +x ASCII-script.sh
                ./ASCII-script.sh
        