name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        -   name: Checkout Repo
            uses: actions/checkout@v4

        -   name: list and read
            run: |
                echo "my first Github Actions"
                ls -ltra
                cat README.md
        
        -   name: generate ASCII artwork
            run: cowsay -f dragon "run for cover, I am a DRAGON" >> dragon.txt